# Generated by Django 5.0.6 on 2024-05-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('fling_power', models.IntegerField()),
                ('fling_effect_id', models.IntegerField()),
            ],
        ),
    ]
