# Generated by Django 5.0.6 on 2024-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100)),
                ('generation_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('power', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('target_id', models.IntegerField()),
                ('damage_class_id', models.IntegerField()),
                ('effect_id', models.IntegerField()),
                ('effect_chance', models.IntegerField()),
                ('contest_type_id', models.IntegerField()),
                ('super_contest_effect_id', models.IntegerField()),
            ],
        ),
    ]
